filenames = "^.*(?i:htm|html|[aj]sp[a-z]?|js|php|xml)$"
last_modified = nil
sensors = {
  ["re_script"]	  =  "[^=]=RegExp;",
  ["ev_script"]	  =  "eval\\([A-Za-z0-9]+\\)",
  ["ru_script"]	  =  "(?ims:<script[^>]*?\\.ru[^>]*?>)",
  ["ss_script"]	  =  "<script src=[^>]*?(?i:php|js)[^>]*>",
  ["nu_script"]	  =  "(?ms:(?:[x0-9]+[+/*\\-]+[x0-9]+,){10,})",
  ["base64"   ]	  =  "base64_decode([^)]*)",
  ["ck_script"]	  =  "<script>check_content\\(\\)</script>",
  ["un_script"]	  =  "(?ims:unescape\\([^)]*?\\))",
  ["9t_script"]	  =  "}}}eval\\([a-z]\\);}}",
  ["07_script"]	  =  "000007\\.ru",
  ["ar_script"]	  =  "cheapairliney\\.info",
  ["wk_script"]	  =  "<script[^<]*?wkoder[^>]*>",
  ["bh_script"]	  =  "document\\.write\\(unescape\\(''\\)\\+unescape\\('%3C'\\)\\+String.fromCharCode\\(105\\)",
  ["fc_script"]	  =  "eval\\(\"String.fromCharCode",
  ["pn_script"]	  =  "document.write\\(\"<if[^)]*\\)",
  ["rd_script"]	  =  "document.write\\([A-Za-z0-9]+\\(.[0-9A-Fa-f]+.\\)\\)",
  ["ht_script"]	  =  "(?ims:</html>.*?<script>.*$)",
  ["al_tag"   ]	  =  "(?ims:<[a-z0-9]{14,}>)",
  ["ez_iframe"]	  =  "(?ims:<iframe[^>]*>)",
  ["dn_iframe"]	  =  "(?ims:<div style=\"display:none\">[^<]*<iframe.*?(?:/>|</iframe>))",
  ["vh_iframe"]	  =  "(?ims:<iframe[^>]*?visibility: ?hidden)",
  ["c162_iframe"] =  "id=\"c162\"",
  ["tx_iframe"]	  =  "(?ims:textarea[^<]*?iframe[^<]*<)",
  ["go_iframe"]	  =  "goooogleadsence.biz",
  ["ol_iframe"]	  =  "<iframe[^>]*?onload[^>]*>",
  ["uknmv1"   ]	  =  "UKNMV1",
  ["wr1ite"   ]	  =  "wr1ite",
  ["glondis"  ]	  =  "glondis.cn",
  ["afterhtml"]	  =  "(?ims:</html>.*[^ \t\r\n].*$)",
  ["eroticweb"]	  =  "(?ims:eroticweb\\.ru)",
  ["gifimg_str"]  =  "gifimg\\.php",
  ["fdc_str"]     =  "fairwaydrycleaners",
}
